### PR TITLE
show default pool information on pool liquidity widget and polishments

### PR DESCRIPTION
**Pull request by pimato**
fixes:
https://github.com/protofire/gnosis-conditional-exchange/issues/766
https://github.com/protofire/gnosis-conditional-exchange/issues/765
https://github.com/protofire/gnosis-conditional-exchange/issues/764

### CODE REVIEW

**Comment by fvictorio** [comment]
There is a small conflict in `market_sell`.

**Comment by pimato** [comment]
conflict should be fixed @fvictorio

**Comment by gabitoesmiapodo** [comment]
@pimato I'm getting this:

```
gnosis-conditional-exchange/app/src/components/market/sections/market_sell/market_sell.tsx
TypeScript error in gnosis-conditional-exchange/app/src/components/market/sections/market_sell/market_sell.tsx(153,10):
Property 'isLiquidityProvision' is missing in type '{ marketMakerData: MarketMakerData; title: string; toggleTitle: string; }' but required in type 'Props'.  TS2741
```

**Comment by pimato** [comment]
> @pimato I'm getting this:
> 
> ```
> gnosis-conditional-exchange/app/src/components/market/sections/market_sell/market_sell.tsx
> TypeScript error in gnosis-conditional-exchange/app/src/components/market/sections/market_sell/market_sell.tsx(153,10):
> Property 'isLiquidityProvision' is missing in type '{ marketMakerData: MarketMakerData; title: string; toggleTitle: string; }' but required in type 'Props'.  TS2741
> ```
yeah sorry, my fault. Gonna fix it now!

**Comment by pimato** [comment]
@gabitoesmiapodo why did you reopen this?

I have prepared a new PR without any merge conflicts here:
https://github.com/protofire/gnosis-conditional-exchange/pull/776

**Comment by gabitoesmiapodo** [comment]
@pimato 

Oh, sorry, it was closed but not merged. Branch should be deleted too.

Does that PR close #766 #765 and #764 ?

**Comment by pimato** [comment]
> @pimato
> 
> Oh, sorry, it was closed but not merged. Branch should be deleted too. I think there's no need to create another PR to solve conflicts.
> 
> Does that PR close #766 #765 and #764 ?

yes, lets close this PR here and discuss it in the new PR

**Pull request closed without merging**
