### PR TITLE
Replace hard coded category pickers 

### PR DESCRIPTION
**Pull request by nickplace**
by querying the 20 top categories from the sub graph.

Follows https://github.com/protofire/gnosis-conditional-exchange/issues/801

### CODE REVIEW

**Comment by pimato** [comment]
Hey @nickplace this looks great!

Only a few things:

Could we have the Market State dropdown to be dynamic based on the items? Currently the height is fixed and the scrollbar is also visible:
Screenshot 2020-06-29 at 15 03 41


Should:
Screenshot 2020-06-29 at 15 02 11

**Comment by pimato** [comment]
Also something happend with the filter icon here:
Screenshot 2020-06-29 at 15 05 11

**Comment by pimato** [comment]
The non-active items should have a greyish font color, currently:
Screenshot 2020-06-29 at 15 05 49

should:
Screenshot 2020-06-29 at 15 06 27

color: #757575

**Comment by pimato** [comment]
Why is the query limited for only 20 categories?

**Comment by pimato** [comment]
Also, once a user clicks on a different category then `All Categories` the All Categories is not pickable anymore:
Screenshot 2020-06-29 at 16 04 30

**Comment by nickplace** [comment]
> Also, once a user clicks on a different category then `All Categories` the All Categories is not pickable anymore:
> Screenshot 2020-06-29 at 16 04 30

Fixed in [fc09aa8](https://github.com/protofire/gnosis-conditional-exchange/pull/851/commits/fc09aa8399abde3db672606ba6c106ab20e0f4ac)





> Why is the query limited for only 20 categories? How do we evaluate the metric "top"?

Categories are should be automatically ordered by most open markets. It's being done on the graph's side by @cag 

I changed it to fetch first 100 categories (not a very heavy query so lazy loading shouldn't be necessary yet). Still only getitng 15 or so categories back from the server.

> The non-active items should have a greyish font color, currently:
> Screenshot 2020-06-29 at 15 05 49
> 
> should:
> Screenshot 2020-06-29 at 15 06 27
> 
> color: #757575

Fixed



> Also something happend with the filter icon here:
> Screenshot 2020-06-29 at 15 05 11

Fixed in [fc09aa8](https://github.com/protofire/gnosis-conditional-exchange/pull/851/commits/fc09aa8399abde3db672606ba6c106ab20e0f4ac)

> Hey @nickplace this looks great!
> 
> Only a few things:
> 
> Could we have the Market State dropdown to be dynamic based on the items? Currently the height is fixed and the scrollbar is also visible:
> Screenshot 2020-06-29 at 15 03 41
> 
> Should:
> Screenshot 2020-06-29 at 15 02 11

Fixed in [adf355f](https://github.com/protofire/gnosis-conditional-exchange/pull/851/commits/adf355f7567b8502a5ee3f8ae5257d2eda143b99)

**Comment by pimato** [comment]
@nickplace last one:
Screenshot 2020-06-29 at 22 52 41
Screenshot 2020-06-29 at 22 52 36

**Pull request merged**
