### PR TITLE
New market overview widget

### PR DESCRIPTION
**Pull request by KadenZipfel**
Closes https://github.com/protofire/gnosis-conditional-exchange/issues/802

### CODE REVIEW

**Comment by pimato** [comment]
Hey @KadenZipfel @nickplace contributions lead to some merge conflicts. Please resolve them.

**Comment by pimato** [comment]
the outcome indicator should use font-weight bold:
Screenshot 2020-06-30 at 10 47 55

**Comment by pimato** [comment]
the filter section button is missing:
Screenshot 2020-06-30 at 10 52 56

**Comment by pimato** [comment]
Now that we have space we should actually show the whole description of the sort criteria. Currently:
Screenshot 2020-06-30 at 10 54 39

Should:
Screenshot 2020-06-30 at 10 53 34

**Comment by pimato** [comment]
if Total volume is the active sort criteria we currently show `0.00 DAI Volume`. We need to add a separator between the amount and the volume description like `0.00 DAI - Volume`

Screenshot 2020-06-30 at 10 52 11

**Comment by pimato** [comment]
Do you know why 24h volume is showing everywhere 0.00 DAI:
Screenshot 2020-06-30 at 10 58 26

**Comment by pimato** [comment]
For the newest description inside the market list item: Currently the description is:
Screenshot 2020-06-30 at 10 59 59

We should make it consistent and replace `Created Jun 25th, 2020` with `Jun 25th, 2020 - Created `

**Comment by pimato** [comment]
For the sort criteria `Ending Soon` is the description inside the list item missing, currently:
Screenshot 2020-06-30 at 11 02 44

Should be `Jun 25th, 2020 - Ending`

**Comment by pimato** [comment]
The dropdown should have padding-left: 25px:
Screenshot 2020-06-30 at 14 02 12

**Comment by KadenZipfel** [comment]
> Do you know why 24h volume is showing everywhere 0.00 DAI:

Seems to be working for me, although it does take a bit of time for it to update.

**Pull request merged**
