### PR TITLE
(Feature) Update overview section

### LINKED ISSUE #272: Update Overview Section
It should look like this https://zpl.io/bAng7yp

Progress bars implemented on https://github.com/protofire/gnosis-conditional-exchange/issues/249

08 - Conditional Exchange - Overview : Balance

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #272 

It should look more like in the designs (https://zpl.io/bAng7yp) now.

I had to update the button's look, so you'll see I've modified files apparently not related to this PR (but they were).

**Screenshots:**

localhost_3000_(Laptop with MDPI screen)

### CODE REVIEW

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero 

Yeah, I saw the error, but I'll implement a new design here https://github.com/protofire/gnosis-conditional-exchange/issues/266

I'd rather not fix it here to change it again there.

**Comment by fvictorio** [comment]
This is not showing the winning outcome when there are more than two outcomes. (I guess there's a `> 50` somewhere).

image

**Comment by fvictorio** [comment]
Also, maybe this PR is a good place to reduce the number of decimals shown in the price column?

**Comment by mariano-aguero** [comment]
> Also, maybe this PR is a good place to reduce the number of decimals shown in the price column?

@fvictorio I solve this problem in the last commit

**Comment by mariano-aguero** [comment]
> This is not showing the winning outcome when there are more than two outcomes. (I guess there's a `> 50` somewhere).
> 
> image

@fvictorio same here ...

**Comment by fvictorio** [comment]
Sorry, I just noticed that that commit also solved the issue with the winning outcome. That being said, there's an issue:

image

I fixed this in the latest commit.

**Pull request merged**
